name: Deploy to DigitalOcean App Platform (disabled)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Optional note for the run history'
        required: false
        type: string

jobs:
  notify-disabled:
    name: Deployment workflow disabled
    runs-on: ubuntu-latest
    steps:
      - name: Skip message
        run: |
          cat <<'EOF'
          The DigitalOcean deployment workflow is currently disabled to prevent failure notifications.
          To re-enable automated deployments, rename `.github/workflows/deploy-digitalocean.yml.disabled`
          back to `deploy-digitalocean.yml` and ensure DigitalOcean secrets are configured.
          EOF
          echo "Workflow skipped. See docs/DEPLOYMENT-GUIDE.md for manual deploy steps." >> "$GITHUB_STEP_SUMMARY"
